import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const context = {window:{}, performance:{now:()=>123.5}};
vm.runInNewContext(readFileSync(new URL('./res1c2_runtime_profile.js',import.meta.url),'utf8'),context);
const probe=context.window.dao2RuntimeProfile;
probe.record(100,'{}');
assert.equal(probe.stop().rows.length,0);
probe.start();
probe.record(200,'{"save_total":150,"save_encode":100}');
let result=probe.stop();
assert.equal(result.rows[0].endMs,123.5);
assert.equal(result.rows[0].spans.save_encode,100);
assert.equal(result.rows[0].totalUs,200);
probe.record(100,'{}');
assert.equal(probe.stop().rows.length,1);
probe.start();
for(let i=0;i<10001;i++) probe.record(1,'{}');
result=probe.stop();
assert.equal(result.rows.length,10000);
assert.equal(result.dropped,1);
probe.start();
assert.equal(probe.stop().rows.length,0);
console.log('PASS: runtime profile inactive/start/stop/reset/timestamps/nested spans/bounded buffer');
